apiVersion: v2
name: homarr
description: Homarr — homelab dashboard landing page
type: application
version: 0.1.0
dependencies:
  - name: homarr
    version: 8.19.0
    repository: oci://ghcr.io/homarr-labs/charts
