cloudflare-tunnel:
  cloudflare:
    account: "5c7c843721216f7bad00bbd8a4520982"
    tunnelName: "k8s-tunnel"
    tunnelId: "597f628c-a27f-4b37-a41a-ef1a06303977"
    secret: ""
    secretName: tunnel-credentials

    ingress:
      - hostname: auth.home.daandewilde.be
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: immich.home.daandewilde.be
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi