image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent

replicaCount: 2

# Security items common to everything in the pod.  Here we require that it
# does not run as the user defined in the image, literally named "nonroot".
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

# Security items for one container. We lock it down.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi