sourcePVC: "immich-postgres-data"
destinationPVC: "temp-longhorn-pvc"

namespace: "immich"
size: 20GB

image: alpine:3.20

command:
  - /bin/sh
  - -c
  - |
    apk add --no-cache rsync &&
    echo "Starting migration..." &&
    rsync -aHAXv /source/ /dest/ &&
    echo "Done."