sourcePVC: "radarr-config"
destinationPVC: "temp-radarr-config"


tempPVCName: "temp-radarr-config"

namespace: "servarr"
size: 5Gi

image: alpine:3.20

command:
  - /bin/sh
  - -c
  - |
    apk add --no-cache rsync &&
    echo "Starting migration..." &&
    rsync -aHAXv /source/ /dest/ &&
    echo "Done."