---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCTgoDuJKSjxgPvXMe94eJnT27HvLyiQDexcxOS1UH5em8kpT9gRACo12yDsxSfViHz4hyoHv0fudjDLcAN3I7BNhh56dMmDIrafK01O1+xoe+9ewLuo8XqPVo9U4kjbL4zVoHNTxzS7H4MNTQGyZccct+N1QbgUsOYHDtw6a5DDaAttfs0ojSDAtu+p9WaLpbpIdXZAj00nbzpfcRyM9d7BlBBY9fvDYhPWiEVwcfP4GPzohIa7UBuGUwcY34brx0Bb7sNg+ALNOCIwLSLBUUUp+dskVfjpNJl83HemkJX4YFeYnoIXBSKGpQlLlzNJAzIf2I99M20BzclwRK1MCobmK5/GfFW4I34PPHf9DAlTdXuUqrKQ/hO1HeZ8K8EW814HMM61arzq0ZjD4r0twTmZb0qldlOzF2kmMIDRJ+kwVUY60vu14eQUsKS+iC7c+vTSa2BwgfN4O3UwYntwZleaYmfxbT4x2re2Mqh9V+TpHCj6asFNHxQWR/d14DGydRTRyrSw1JxagEZzJulQdff8cZyULrma5yB8v8XuojPhDETPlpbadq90jc38g0IG1zIqkF0496buYB0HYG/08BwLr+/gpGGHKtgZobUo6bq8TgeWFpQquTPVU+9xnlRsSCT31CuMKD9lXRnFBfbmWu6P6ekwdLDswEJvP//bLlTTZ9FPSJR4Y/a3ScYJ6MqDKiKXs/ihP3eoLv1A93uKHPzJUlpep3TDOzu5O8FgATWfF8/EIFD9JXvfaZO7y+aEIyA6gzvXQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
