apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-secret
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    admin-token: AgA11K0kuiM9Uok8tShu72OOakritU+iRY3MmuWPTl4Jj+GLFpct6+85bPiv13ve21Bvukp48kRORhlmKqckuZXr1vyg+5IdHjYickSRdMPnN5sSA1fvoZUjV+B75BEcM88obweKhz0SnD0iaHqKNUBbuht2YG+vMwlqCK92rJEej0BTFzgz4pyJEffTlV56gDDMzvOkvCLwzd95bU6pNNhoDp74swkj/Kum4Ylx6Ozhm1+t2IujXs+yXEQCEpe3/1QCBDNzW8iyFQeed9e7KX3pnzhYGolXJWugZE3R19hl3VN3kTrnvpjYiESmshfxZAbL+PMXmy5UdS9vcCTBk4+XHIyHQQWw5cxwde8LdD7F2zBD/sZZCH3rLZxzdL0xoL9h5/NG9uWRPAy/XgWc0kz0zkRfCou5SG7VduxvZmvE/w9uUsAMj7GiT8DzgjYoWca5ElcNrmhF3/2tfKC0rF2ouCdNY9wgaphtVlmQdMDQfju8dGzWMVaJODiMt+gSgR6f0hK343R/tH3g524y9msQnmy0+FjAPzkAYYScOm3igzfRinaA1kCIDH7JLi8JfdXmi9MsmxYM9cHrN6Dh3DyIneKmfEpzEgPVs++hnIGhaRTxQja4Iv+F0vjvKtqnLMmyPq+wrpS+410AvBMGnOzjkXFImEdBbZnEsmUKn/4vb8VW0XW2ax0AkOJ9hdRJZCKiLzGHbhjWmEDNhbPHZhw249bn8zCB5bDHv2AiV3uA+oXSgPmF/lSM3U9r8zCjmLVLHfptP1j5jmi7yQyHnVEw
  template:
    metadata:
      name: vaultwarden-admin-secret
      namespace: {{ $.Release.Namespace }}