apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.home.daandewilde.be`)
      kind: Rule
      middlewares:
        - name: pocket-id-admins
          namespace: kube-system
      services:
        - name: adguard-web
          port: 80
  tls: {}
