apiVersion: v2
name: cert-manager
description: cert-manager + Let's Encrypt DNS-01 issuer + wildcard cert for *.home.daandewilde.be
type: application
version: 0.1.0
dependencies:
  - name: cert-manager
    version: v1.21.0
    repository: https://charts.jetstack.io
