apiVersion: v2
name: pocket-id
description: Pocket ID deployment with Traefik IngressRoute
type: application
version: 1.0.0
 
dependencies:
  - name: pocket-id
    version: "0.0.0"
    repository: oci://ghcr.io/matslarson/pocket-id-helm/pocket-id