apiVersion: v2
name: pocket-id
description: Pocket ID deployment with Traefik IngressRoute
type: application
version: 1.0.0
 
dependencies:
  - name: pocket-id
    version: "v1.0.0"
    repository: oci://ghcr.io/hobbit44/pocket-id-helm