pocket-id:
  image:
    tag: "v2.7.0"

  existingSecret: pocket-id-secret
  config:
    PUBLIC_APP_URL: "https://auth.home.daandewilde.be"
 
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 5Gi
 
  service:
    type: ClusterIP
    port: 80
 
  ingress:
    enabled: false
 