vpaObjects:
  enabled: true
  targets:
    - name: vpa-vertical-pod-autoscaler-admission-controller
    - name: vpa-vertical-pod-autoscaler-recommender
    - name: vpa-vertical-pod-autoscaler-updater


vertical-pod-autoscaler:
  admissionController:
    enabled: true

    registerWebhook: false

    certGen:
      enabled: false

    certManager:
      enabled: true
      issuerRef:
        name: "letsencrypt-prod"
        kind: ClusterIssuer

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  recommender:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  updater:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  crds:
    create: true