{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-id.fullname" . }}-config
data:
  TRUST_PROXY: "true"
  TELEMETRY_DISABLED: "true"
  {{- range $key := keys .Values.config }}
  {{ $key | snakecase | upper }}: {{ get $.Values.config $key }}
  {{- end }}
{{- end }}