---
apiVersion: v1
kind: Service
metadata:
  name: pocket-id-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.4.36"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/instance: pocketid
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http