apiVersion: v2
name: sealed-secrets
description: Bitnami Sealed Secrets controller (umbrella chart for ArgoCD)
type: application
version: 0.1.0
dependencies:
  - name: sealed-secrets
    version: 2.16.1
    repository: https://bitnami.github.io/sealed-secrets
