apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alloy.home.daandewilde.be`)
      kind: Rule
      middlewares:
        - name: crowdsec-bouncer
          namespace: kube-system
        - name: pocket-id-admins
          namespace: kube-system
      services:
        - name: grafana-alloy
          port: 12345
  tls: {}
