apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-longhorn-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.size }}