apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wardrowbe
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wardrowbe.frontend.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: crowdsec-bouncer
          namespace: kube-system
      services:
        - name: wardrowbe-frontend
          port: 3000
  tls: {}
