apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wardrowbe-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: wardrowbe
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
