apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    SECRET_KEY: {{ .Values.secrets.encryptedSecretKey }}
    NEXTAUTH_SECRET: {{ .Values.secrets.encryptedNextauthSecret }}
    OIDC_CLIENT_SECRET: {{ .Values.secrets.encryptedOidcClientSecret }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
