apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wealthfolio.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wealthfolio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}