apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    WF_SECRET_KEY: {{ .Values.secrets.encryptedSecretKey }}
    WF_AUTH_PASSWORD_HASH: {{ .Values.secrets.encryptedPasswordHash }}
    WF_OIDC_CLIENT_SECRET: {{ .Values.secrets.encryptedOidcClientSecret }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque