trivy-operator:
  trivy:
    ignoreUnfixed: true
  nodeCollector:
    volumeMounts:
      - name: var-lib-rancher
        mountPath: /var/lib/rancher
        readOnly: true
      - name: etc-rancher
        mountPath: /etc/rancher
        readOnly: true
    volumes:
      - name: var-lib-rancher
        hostPath:
          path: /var/lib/rancher
      - name: etc-rancher
        hostPath:
          path: /etc/rancher