---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-oidc-config
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    config: AgA1akckPX00g3z0LGzt2wuMYIWebvrekxBdM/NCYeszW47k5q9vq05QKEUrD/bqVAmMBQaqE34NOV9QGGJYjOQ+fXh62/MyIf/3IUlaHMP/cVlrV1mryOyKSRcMm9RwFxnTLSraE3RY6Ixs2vBaUS6e3AEfPWrf1ETIQhVYpt5ENcswVzGEj4q2rD5eRsvJwiuuwqx5cOBzHJEy6ZprDalHCzK1nzVwBLQdyUhDB8MU+2wVMpiUiDMWSHUJHWokBcDky83jDZyhbfQCcaszIH1pyBq+opy0GXXOw889W7q0Gw1nBUOryt5bsf3bmcsQW5iTm3BFNemArJNsXXFySYWyZsneId/NDPoBj1gG2SNJ6Bgis5bZd0OAQ/ikVDBa1GuQPRZhpwZ60n1yAdZoUv1d+bKBKdrxHY7edGxgxxb8zTXTlPZzVhNrpV98/9woexZSn+o5vnZUscALfjQvUb17yX987m2M4MpKCT2SeGfsnx5BqhcQEahTxPFJDb2D1TLaZ+GI7gJKmMqBh/k2EEy1r8z1665fUaGg011wBpzWj+CcRrN4oPh4BBHc/nfcv5IHw2HLHOIvVK+P0Ja8EIOCIRiFWpq85Zhv2ABkhFcAyupwVaNRQjMSVkV+ViZrl09qWHC+qcKjWD3ipGyP+JGh4lkI8d5XqI4/vkw7rdCotYq2JRefwLcFqpZrSzBd0Zati7QzjD6UoPSxj1NL5u+dTFA7EyQ/g8vRN1ZTZOGdjg7LVnUpAmLrjYK7/nU32Qty22dlMoD7VQKpbPo83SCvYDYuMMWO7Jk90JPIPFwhc6pmkWSpMY0bpUJErINzJ7qGXVAAzQdmlWUIxh8WxV+wO44MnThl4cCSa9RwqjZ14hIN57CXmmz8RJMlzM1wmV3rL3u6mmZh5a8isR3jvuRN5Llu+JsUqmuCoKTiHS7a0WGJ957EylpegRdURqP5m3QoZiTOOm8i6ZituPZJ6WV7tzPmai5VQhNUjm/WLiyxIksMsBdcbpjkcESQYWBoBAwEeCJlqwHeB+SYf/vcot/fSX6Kve8wSZIxC+JrVxsLREYNIH5SOlmgLPs22V35gyLSWB808si1
  template:
    metadata:
      name: paperless-oidc-config
      namespace: {{ .Release.Namespace }}
    type: Opaque
