---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgres
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgAiKYMiGKdwxkhKs5qWR4jbUBli4metdjGh2vQKLwXDAr6kjd6NCiDowq6Yvowv/D38CdFr3pmEX3WBur1Al0EMwWncR3xRfoewW8ersVlAkTD1u1lmfNU0RpcsNuyFTbfcufUDi9bNbYbOYSTb1kE2zJ7fl9uFgTIxiNXyHOzWWfcHUElVcn1y7nFTKj3G2icAJJpqBMpxwJI7xHAufx5ReIOPsBY6IDWUQAtxyfuvYz1Iy3EAnsmfr1KUBlD3N+vKLqfTFIx0ToDHl7fYdrDxo6XB1UHEchXXUA5AIo6TGhe/QWFNWfOPQa72VQ04d9AxvJZjSCzPMVV7vrSS98A8L2bsNidGaJd2YmrufWpacuJ4nskigKK4R42ecxTwq8ThKN+ab1r3FLr4iZomMMRhKz+O2rbAlb+AZGLfMGBK+zUGcZWlfvizqSldPjOeNpze5XQ3m2jTL3z9fKAKmDGvQyfePD3AUluG2Hen5Hq4gGnkZRd5d0w1QltKB2u30FChtexp1B9FDQkVPRcCrbZ/moZ90nDTDEmM3zy+ZpRUEBzbCU6IMCKUyGa5qMiX9POr2vFi3ilUsFds0FVPBY6GUjkf6CkEj29bETY3w8mlpHjPAXd13b9D4tU4qIofdnPjC1RLW6b0A7/hUBkTSJuLlXn4CBnpdLn+IcPcHTpljnxGRklzzB1OVZBrL+GTP/3+QFYjVkK9XblhVXk=
  template:
    metadata:
      name: paperless-postgres
      namespace: {{ .Release.Namespace }}
    type: Opaque
