---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgres
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgA7ZuGeSh0tf6m2noL99AtQsNsrnX1GnfBrwKIHr+w3IAw1AqwKaGDjAw7duM9C502ZWRIE8CNihGym4kQ7krRi24D4Q6WW91h1H7XryU9CnN3L2ZTWBiKXqeZPsLzxV6VPJq7nKMqu7QzZ86B6UEd+GDEkMgBZ0tw778/CWyWBkxnFjcacfdPYSb+ezE7yFSfT+eLKVNn4pglfZOHW5nb0Oi0CdvvFUGsQbOjnvR/F5VyUFbLlUpww0iXMGz1No0lHROV2bAoOQjuFlbgHVa+GriCZ3DTju93twguuGgVJTs2+98CHo5qI65JNEOownZOCdPZaQnp/OTHez6yCpIrhdj9Ro9+LZ8lW24Dl2j1T1yeQMgpC3po0sOkVqjusdgVd6LCAzZGDifYMmtepJh+QA9CazldTxhYS2ac3e71vQJ7mzpiuUl31PvUzRVkLMysJGdYLeInDeCrhKkOamk+s1FRuFqVOY5SLjh39wRyyGblJT3gMqFADk/jOD9KOXR+/IAeOEOta/by1nZon+KjgUfBouGfeDNGx72qzWCNRvnnJtuKZ+c8FQKtrZnY5yuQ8cwB4MBRsyFkw6uOYFNOIm66RwRe8ljHpdeEwGcxbNSTOjfAHqcGbUNX5I//FXAYBx/Rw5abX9+e7TKX/OnUcx4mOFf1KyRH8+qPNZCotSjg28o5QNNulzsdjS9qvKm8ABRsriAr8DxiLq5UZ6+5k
  template:
    metadata:
      name: paperless-postgres
      namespace: {{ .Release.Namespace }}
    type: Opaque
