---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgres
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: AgAikUxqcRueuwXGd3IxzvkqBhAfn07ggNC+gt8PLnGp+L6924FEUaoLzaXfb5akxi6Hj0uzf6Iqoe7K4tsUdRqKHYEWnMoc876mvQV10MdZlyv3h3Z9DX1ENYV37UjzISephlrHe4BMF4jDXQEOcChbzEqX/+gXMQcRGpsMfJefI1sRmszWLOVppatr/cVIDU745Mtq9dYvonEOabgPYJerjw7gB6nFx//g4IVwi1VUGfxcDaSGgkNhCF36zg9WhNlOCGXGUL5xumXZ0IHZIlKMlxT2zqq7ft1y6BAP06fDdr9Dp7vxHJ6WXejyjiavJoeC21rlycgtwWpQvhHZdBYZDoVBPy/nizmQSBsBMf/GJrUt+DjQqNjR6PVBH9vItoyXRNXaC9h+VOoD3VvbKQEjihDzl0mAXtjNYK5WMJKYehgQtarXQGNds30OApSWBYmhy+cnYR9Xeunl4QEGmoHfRST2YdnytIfFBPE8YWgJ3RmBtMM8fmpg3WB6zS7u4Be/AqdhJnji5DLjvT9xhCv/1gTRqWL+N4zmKWZ/GAVY+GZXskoTllCSfmPiVZvRSnjniFgxii767n6ByPaw0193hyGa2BvfbeuRvZbRUz6Sq00VBoyb6gOQjuXqHiJIgx/5Joj6laWfS88GS3dtcO6mxsqvFK1dtXhjsfSDUttE2iD2udyGb6NYGkil2GL9kOWdZ4aIKdwaWP98B8U=
  template:
    metadata:
      name: paperless-postgres
      namespace: {{ .Release.Namespace }}
    type: Opaque
