apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres-data-lh
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: paperless-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless-postgres
  template:
    metadata:
      labels:
        app: paperless-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-postgres
                  key: postgres-password
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.username }}", "-d", "{{ .Values.postgres.database }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.username }}", "-d", "{{ .Values.postgres.database }}"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-postgres-data-lh
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
