apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-uploads
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 20Gi