apiVersion: v1
kind: Service
metadata:
  name: beszel-agent
  namespace: beszel
  labels:
    app.kubernetes.io/name: beszel-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: beszel-agent
  ports:
    - name: agent
      port: {{ .Values.agent.service.port }}
      targetPort: agent
      protocol: TCP