apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-hub-data
  namespace: beszel
spec:
  accessModes:
    - {{ .Values.hub.persistence.accessMode }}
  storageClassName: {{ .Values.hub.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.hub.persistence.size }}