---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-oidc-secret
  namespace: beszel
spec:
  encryptedData:
    client_id: AgAZCmKA1yzDE4izGKgvzqEs9/5AKGvJ7gGSoBAevQGZNEHqBr9+vCHs4db0y8CwjuwCyEgf+HErZLsAv479nN+7uWiUOv8Tt//MSiCnQbK3N7HZaukLTP96DeoUITm/fhQFLaSNvTY0hEsbauNtcQmxpJskT1DgqDqOvaI6yuaah7wtBpTfzEryrAtZS8vvR5O1AEa07a5beevVmhgqlU/3g03JfUkJifo4tVxed99M4Cxd6CB+1b6/wBEXe4ns6OOZnS+slkjJM+c5GwAlqkyHPx4s+tWh127s3v2/wapS8xzD4KGIq2xhEJ009eYNWnPHTkQ4Kf1+cfJKRbddPUwFEH/z0GoC/6xF7C3XkebZ80zHGMirXB85gSzFY3zQqJBJe/AJxejQW/fehBkG8YiidSquBt46nwlKrY1wYzpSxAU2FyOlf3L+5BTkDwIH82juLDJhe+ZZGQAaI4LFuACcnxcQ2JWFCazGPjGjQqfPrLZpaoLEv86Uh/949GjynLfPFxRlBM9k3MOJGpjasLTzXqY+hWUV6oD90BkMvYmxr5RF0C7qobvnXhya+RvYyBTSfYQK/ma8H4LCrTjGAdrdxiyqKsXU91giY2mLQPQurGG9qv03+EB2RJDPeNAPpulJiJJLrGfMSDA2BIcib9l8QOxTscojtCoSL4U00NBTMBEbMsnwAHaEGicZNNL+UPlZtrcwyOTWQfGlAIniz5y0CovNNsNQqIRHZW2dJVDNQWEKlB4=
    client_secret: AgCJdCBMfbvE+bzpSQfRKuW4lrq74X7NpCSOMa2QH6f/37M1XMEq79LhQtQlMgzTF0eiM+ny/poqvSfv12ogYYE9bAZrhNNU290IJGNUtH4RzJ6sJm1VPEunU10AcpJUTR1brhxPTAswvR9DeXwPN3iCru9cHg/Z1it63oOKy6hcrPpwgTN0lVmGc6b7ko6jrjW2fE7uxhIZAw1+YG8T/9yCBQnzgvClxyRCL5td6EKKBS7y25GZA2WBA04I9IcLB7tvjB2rlh29yLhHb2MvUfsp8BWAh+R1NmGAkw8vOQw6P7tYI9Heknni2F/5TIQHx+LCGy4+nCWb/tKYmzzLccLh8I4R18S3ZK4DA30ArMTqwcSuJK1rfA5EjLyOm4pwBH6wJzARYHRGwz1ZTG6ISd3HHgGCItRn8zcHvSMsJ+QTzTbKdOUhXq3CHQ/5/4rtmfNv1ngFam610aeGUiQDmmhCXn2xNeg/cBFZSO+4pRuqRa4RYax0kpETqhL2WXFXk6GeJSpOCAq5X3wi8VO+f/K2Ip71fGp9XO0D/bNnJ2N3OttYp4sVEFzkevvXNdnSMAIJYhYYI5RTTK1ImpEuyr1Ad0Qq8G7svKegldwH2udH2mhm/54tSiKh/Ak3maMpakNGehWCOmnRzvQY4gEcssKig5eWdYP+bxcl7CY5A0OMd45zzAFlIGLbzfQmgORMp5oVpLq9zVDyqXdnBcyX6i8txDwXv9Cnn7gOH+vd6iJ8GQ==
  template:
    metadata:
      name: beszel-oidc-secret
      namespace: beszel
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-agent-secret
  namespace: beszel
spec:
  encryptedData:
    key: SEALED_AGENT_KEY_PLACEHOLDER
    token: SEALED_AGENT_TOKEN_PLACEHOLDER
  template:
    metadata:
      name: beszel-agent-secret
      namespace: beszel
    type: Opaque