apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-appsec-custom-config
  namespace: crowdsec
data:
  jellyfin-exceptions.yaml: |
    name: custom/jellyfin-exceptions
    pre_eval:
      - filter: >
          IsInBand == true
          && req.URL.Path startsWith "/Sessions/Playing"
          && req.Host == "jellyfin.home.daandewilde.be"
        apply:
          - RemoveInBandRuleByID(932370)
          - RemoveInBandRuleByID(949110)
          - RemoveInBandRuleByID(980170)