apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "printstash.fullname" . }}-vault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "printstash.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.vault.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.vault.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "printstash.fullname" . }}-backups
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "printstash.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.backups.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "printstash.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "printstash.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.db.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "printstash.fullname" . }}-staging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "printstash.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.staging.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.staging.size }}
