apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    VAULT_JWT_SECRET: {{ .Values.secrets.encryptedJwtSecret }}
    VAULT_OIDC_CLIENT_SECRET: {{ .Values.secrets.encryptedOidcClientSecret }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
