apiVersion: v1
kind: Service
metadata:
  name: {{ include "printstash.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "printstash.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "printstash.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
