apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-db-app
  namespace: sparkyfitness
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    username: AgAxHqm3RiBxUSJgLf3dcOd39OG8fIP+AmcKd3uCqDH+c+UDV2qLUeA7oYnb+vNmnNfCs6QM/rQmiB99qGd9kCpDkuhUnNzUWnYJHXjiEQOoP0HNze1lkxU15cOstY7FhGPrAPa8qlxbay1VEMy0GhrBQUSlt8fXXH6F65ke4GEIw2wN38ZGC9CMR3FGN4+ruEB1fTlOn4RHXkiuJSQcbpHvNzjbbahJ9mAwLaNRwrIYDe1Yqw7BvnRjuzEC2Q60K00USJJ26WVfoiQUtrtr2x4+ZgRfeaxLN7vWzdloLNRjjNAno2K4HOtvcS271SACVBFK1RD64ccgrp8BmqJxQ9muMoP0CZLUyor1C8DNUV24N+urrvEc/l/rDEQA0oTI4M4lqZh46zJD+DxhqHf9blkQI8Zs907S/tIC/HFmuZ0gox2K0z06QX6859WliKANsH46Z1fSsTsEsoURZ3YEh25xqyMvTQj7pm9n2CFnp2/GPu/POAWfJ+Hrdbe6dKu7oMkyk1W1PrjVC4Ct5wTRlICs3Aw9P5vOCfRcdkD76hrB4MFxvQTvQ3fNAu3OOzitEc2kX9+YCo0ln3W1/KDnFjyPDgwWhQvUAmn7MtREzxeCVhpnaMYrght6khhHejMzDlAxniCpfM+i9UbB0fWENgebotDVJuiDFzdRIexf4gFVWo6lbnTj07KyEOv74CklgYYw9qD+gAsbybsLgjR+
    password: AgB+vr29AWQ9YH5eAQ07UY31p0CZibzqF6RQzYZlmFhS4pVB+IyodvAMOlxZroVcCKGrftbi0BmADeeGHh7rDu/kW+lvplQXdRbt7TinDhfbX4NdQIjw6tRSieMTwcf8b/y8ZiYRBuor+nWoJu7QqlmAwMDI1uJ2FlHhcAyC+FUALMT20gMSOQSCQh85V/w5s3s95DvjymVkwSkF9VeXvs+zkTfGnORspyMvfbzlrIPYuMitmwsrUxG+5mz/lZ4sNrBSLOjq+O8BxNGhTk/FfSexyWN/A+YMyxKqh6nJi3ehla5f5xOGr2d+KCiES6IuViFRyr+LLNQmGXEYnsbSG601i82r164ylLjtBy3htn4Xkq6fswc/+zlZFzs1LfoyCYCGSymVgBtNXihWJaIUG0DA1w+nl2SPogAxIsxItykKq+7boKwmqEffj/YFGaljC9fB+FLZynZGY5WZIOF15UpIadOIk3d5zE9IKgi5TLmv6Lf9kas05ktQzAJDf1McjLsCTrdTS4IY/X4ZmrC/6JyCVH2ZRa+YBjkQmpqyq6I0089e4K7g/6zZA06VGk2/A/Omd6PkJOGnV+VpmcHjtUcQphKgA59gD8Ul8FhAO7to3JpmZTXwjA9kV8ptimZVsd8FS+tCU5qwXyOBLUCAPxnXkdZ5QDMi+tmCRVLd39dsHYk0jjU0cWXfogR0ZFQ5gnHn/XSUW3Y/TgBkmVS4CrZs
  template:
    metadata:
      name: sparkyfitness-db-app
      namespace: sparkyfitness
    type: kubernetes.io/basic-auth
