apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sparkyfitness-db
  namespace: sparkyfitness
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  storage:
    size: 20Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  bootstrap:
    initdb:
      database: sparkyfitness
      owner: sparkyfitness
      secret:
        name: sparkyfitness-db-app
        
  managed:
    roles:
      - name: sparkyfitness
        ensure: present
        login: true
        createrole: true