apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-db-super-app
  namespace: sparkyfitness
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    username: AgB/AYwoMA7t70hAnfoGcwcB431KwLzcAddxNy+lSrAD4RlWO1vR0u/78jLxgtM/zg9qgaBxdlPD1J8noBxE0QlJmvvY2tJCsm02MITKat9EeFiluqzlMXFoVNknEWB3qA3tVotjFmTDi9v11PJnhB5lTfchGsIVuZZ+1tBz4ohFyFNhY2rNULOlVDIOKTsNfQjuuoBFmuDcjUpD4CCiR1mMMymHL3bGgHohdhTqWM685SpwTkMA4jPVaXQbwVJMgbJcGR0aWXwz0Ro/i8JaMAbLgHbUhL6OrJ50JOiMB6eKaBP1ifkfNR9321blnf+uHJdZBEmS5e/gYr8O8Jw1suBKJWL57Ww73ey32+xxEoa2gEEAcX1ox0uaSTeD/hvId5eiK82jLao8FD5ulytlojWnCl6n9dxi7jcqP7LHDSJG3XxA9pGsvPiGTPilbQCTeLYf2s043w6xO40EHjU8kPcy0bxilLyFEomx211GHTVXkhEOJ8vHdWY9fzcBCEDurVvv9Zns7B0jaX5ubKX72trS7o/IPJs+bFAGjkk9IsfPciXsrzZ5fZj3tb7ykQwvTcPsk1vo2yzqBwoMEHAcbhOy/zhSG83LMM9r3VI+CHpImoZ7dGEwEcegdARON+HJCfxh1axIjKUNdWbyEbhl2C9QWJ9so/pujcPn0DaYVKBJ2Dy0kQT8hhouXkcISQIF/GwRW4kREw2SOyYq85M00xsXw5s=
    password: AgCMqJVBbd5xCScakz4eiamVk+Tmtq1Liw4f2npMGct1U1C9SjJcWGYnt96je7E2qVw1dLqyr0fPkKSE8HpddLzByq2J01aBEETX2wogjSCu9tJyGVHqhj0m5pMm62b+E8yomIojFSo4yiT12PPshQ7j+p3tbWyX06BrEMh3FWK17X+XGTWhhODNtXcS3TAcoEnU7pl6SI/JsemxtzQqI39uqKe5VmVQqjeNAUBERy7KOli1rxFX5p1G/8XiRP7YNiKeepKV+BjhP0pdPgOljpP1awPOz1CnF1hWy0j6Qq8AkdGQVKGgo35RLV7sGUi9AJ1FQZ7jAr6FQSgmDnTF/jsYCyEew1M9nLeREeNCMxctGaQGjLByWjf37hLlVdpLUEpD+W746retYRKHvHmCB9sKLBJHjEWvhBp0KBgZg8+URM2m28IqKNZAIrBfevkAKOpFIwyF0oVOChsueOCTkp/5deAMLazxq0W8R9Bs6w7dhgPpS41dc85o+PSuZ1LJHfrHzqYzAQ2n7K7a/5zx8pVZ/0cZW1ljacv5BoX/gzf33uJtDaNTIpKT1LzPaNgvtNrcmk9Fekst4rYx8p1E34J2CxQSz7LA4Yv1ScQ814X8bTfwj4aBDL3s89oJ5YAGtU7IplvGbwuqw2ShNJAbtemgcZ+qQKHxSG1SSRwa+vcWMJXnb4gQgsjWvs0J6S6bAFk72EkvOT+2N/Y66SrL9lq9
    metadata:
      name: sparkyfitness-db-super-app
      namespace: sparkyfitness
    type: kubernetes.io/basic-auth
