apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-db-app
  namespace: sparkyfitness
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    username: AgCC9aiAcFJueUCkIc82yMpOcNlvQxbUSUU4r6kcz1NMS0gTcbCR8ayxyXiYTSc7zRAt594aS6jjfSA7Ojva4vuf8Obx6Ep927qS7EFvFtUCE/Ggv08PJG8aSrjPWDvm60fF3Zh5Lh1TqBexxxWFWKjjOLvRTT0EtEqQyfDd5aivsy3aFud59IM3mDuAm9jDs2BsSpv9jajitfVCnLcbAVwn5sjOlwC08KgP/Y/NxEkMkZeJwAGE6gpZwAXeex6rzSb4z4X8KurX5ij3gmN1QEY1CUkb8tNJq5jPgEqZ8jL+S2kaZEOKidgN4JBDcSTL8DULU/hpu8f+Z2ZCDmLlP7pGlCYHz0csE00Vdv027MhaQDFEdVbaFEIwOdB3Blf/U0QFpPqBF1ALJ41hfyK5GmYT+tByIi3wZRM7uObovV3fIARFiveE2BGSl8KSi46C4NAPiZi+pS5G6eCt/gxKPEAichCttsOz0NagHkp9Rusi1PNJV2r+GMAvUYE0UssYL3zOu7nrDBI8cXJTsg/7Z7R7FDbu0CkbeRKt8l3EVxV1YSLgRkxG4bPHOsBPDoYxEqDEFd2W+wgY7TtpU/yugdA0lsIj9ybajAlTP5QVZtq+MBqusaIC84uwR4hbK7Lnp5xrryqgwWErNQOLWgFV0K5fVKJ6BiQmWk7cYDeCkBYaZCEDFc/jcdW1VDPUVKEOPAMHiIMxFXPBfNq1Jy5A
    password: AgDEPxTUu8q0xH45orgPK5aaLAdTcMyKNiNcSF807Anq2J4FFD+xh+EKfRQnpbbFVI28MciwIDvzlM7kQb3Igf8FJBJQQZbu50AGyxs26ZMLez7TYuwGsSd5GtSB9nRYH//4r1rskyRl1X1J6Op7qegGjFFi2OotWMp78YVHXqH6yemJp1WG1EkOfDEDbvaw/1RPS+PTDUphv99AiwBBKCtR29VIVF2vKiIWDlvM5dAWlGwOME762CodVrSSbfhd1TvXM04tOi8VJhnRAwZkUYYtEXULXdpkW7CMCMCT+2AsvfCcx/eluRcx+mqS9NxnFGm0kefZeTOBfzqwFZwwzW2LIkgQ8WH20n01GQPfzbpdnMForh8ShUqXzunIfkh2LXe2vxXFJCKJXbtVk2kTFCqgwwOyQNJYYZh1VQhUTXHkWLRWMnkGrPfXIfgAlTz2M7UCYs+jkxkPMWPNhpxj7uTTpzcnk82JXshAjCpBRvO62GgZKXoz9GNDkhlaeYOYTPmcvaVq0MBRHAus5h6hCLB8PKLElWN5QcwfLhLyTGF/F9ol9aE1W0UBrHksKXGxZHBgE2mxKe4xaF+xxDOZ0fBbqrgKaqOV1tIjhytHlke6RYp8x/0YwsTxJu4eN7JuxAagUUF6ytkn6IXquRFtNVQQpJ88XdK2+mlS7TabojTGOEPrzKckvpUUXVj9AndxXr59+cizXMYdjuHaWJUH96fD
  template:
    metadata:
      name: sparkyfitness-db-app
      namespace: sparkyfitness
    type: kubernetes.io/basic-auth
