apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCsVrEGxPwaDARX82IefH7LVDnwQFv6ynPkfCqrUFS6/RwAVcwrqbSF4jFATSwPhA+OFQCb2B501glIoyLWf2pfBuwSHEJjsTVmk48ZjB2j6o574EyxtBWvz2h3PgSzWEWOtWKDLD1qTig/mTJumn9QX/79bnIz89Gcqp1dkcxaNLUtCq2p4YS26JOp6ubJLnXfcKDduIYfdBGAc5QSq36SHpQd0w40+D90EyLJB9j67IpsgjobFELT61sIar7VYKw7qyqkpZzvGeUKX8dM/ExVwi3WhE+61HXg6qL00zBoRG5HiPLdSHQeeFYwKlUhKA+fP+r2ogpd1KANb0X8B4ygsufH7gDZSluh1ISWInGs8VcEj7FFHgiPulMMcd792NAjtMOK0fx/LBoq11phIZzbfNhDAHxXQubm9XrYXKDmjhmt6Zj5w2pJbC538YQ5gv3qcSasOr7X7qBWTRy94px2/4UzLzOGqDsnwM1CInrHdrm6YUrYL52rQBEGHXa6BwUdgY1t1B+etnz1bQFlaHBNvprfy//ZAZoB6hjRjrgvLDDhSmmLOCFFmLOVkuACAdfSp2FT7ziMH10xtEbsywh22fyiB4wP/vZW9l67WWeeHl2vgo75iE2jsN/s8XvHBHTD7PNK8sNxqzHI/yQugsvY2iDhWVE0DonsAvWSy0tHIKJoeeu1dpW3vUs5BEFMSHEAdMBnHw5c+S9t9WVrUNm9XRAteDDI4a/qBxjhIHVtW+DcL0xL7Ml0j47ImA==
  template:
    metadata:
      name: pocket-id-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque