---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.home.daandewilde.be`)
      kind: Rule
      services:
        - name: pocket-id-lb
          port: 80
  tls: {}