apiVersion: v2
name: sparkyfitness
description: Umbrella chart for SparkyFitness - self-hosted fitness tracker
type: application
version: 1.0.0

dependencies:
  - name: sparkyfitness
    version: "v0.17.3"
    repository: oci://ghcr.io/codewithcj/charts