sparkyfitness:
  postgresql:
    enabled: false
  externalDatabase:
    host: sparkyfitness-db-rw
    port: 5432
    database: sparkyfitness
    auth:
      existingSecret: sparkyfitness-db-app

  server:
    replicaCount: 2

    image:
      repository: codewithcj/sparkyfitness-server
      tag: "v1.6.2"

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    persistence:
      backup:
        size: 10Gi
        accessMode: ReadWriteMany
        storageClass: "nfs-nas"
      uploads:
        size: 20Gi
        accessMode: ReadWriteMany
        storageClass: "nfs-nas"
    
  config:
    nodeEnv: "production"
    timezone: "Europe/Brussels"
    logLevel: "warn"
    frontendUrl: "https://sparkyfitness.home.daandewilde.be"
    disableSignup: true
    allowPrivateNetworkCors: true
    extraTrustedOrigins: "https://*.home.daandewilde.be"
    forceEmailLogin: false
    disableEmailLogin: true
    oidc:
      enabled: true
      providerSlug: "pocket-id"
      providerName: "Pocket ID"
      issuerUrl: "https://auth.home.daandewilde.be"
      logoUrl: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/pocket-id.png"
      adminGroup: "admin"
      secrets:
        existingSecret: "sparkyfitness-app-secret"
        existingSecretKeys:
          clientId: SPARKY_FITNESS_OIDC_CLIENT_ID
          clientSecret: SPARKY_FITNESS_OIDC_CLIENT_SECRET

  frontend:
    replicaCount: 2

    image:
      repository: codewithcj/sparkyfitness-frontend
      tag: "v1.6.2"

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    env:
      SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
      SPARKY_FITNESS_SERVER_PORT: "3010"
      NGINX_LISTEN_PORT: "8080"

  ingress:
    enabled: false