apiVersion: v2
name: ittools
description: Umbrella chart for IT-Tools deployment
type: application
version: 0.1.0
appVersion: "2026.1.4"

dependencies:
  - name: it-tools
    version: "0.2.0"
    repository: "https://charts.jeffresc.dev"