it-tools:
  replicaCount: 1

  image:
    repository: ghcr.io/corentinth/it-tools
    tag: "latest"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
  
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
      add:
        - CHOWN
        - FOWNER

  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi