bentopdf:
  replicaCount: 1

  image:
    repository: bentopdfteam/bentopdf
    tag: "2.8.2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  ingress:
    enabled: false

  persistence:
    enabled: false

  config:
    logLevel: WARN
    workers: 1