bentopdf:
  replicaCount: 1

  image:
    repository: ghcr.io/alam00000/bentopdf-simple
    tag: "latest"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  ingress:
    enabled: false

  persistence:
    enabled: false

  livenessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10