apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    token: "AgBDVwMTTB2KiSSJYZ6OyWbPNJit4nL3NAsaJP8xnAnheGFzYn1WNddEc9eRGl8tSsakJulXezYaj6XKO6GryDhahyOdirzS9VXx7jLFY3kd52OFm1abUDhx+elHxRyOuxC3HhEryrP3L0KgLkOZBdp1/CqaYldT/1kT1tnX4RXIe+yGkkfSez2N80oU6zZCSDCXhJIwmEw9i/cyEmWf+tdJcX8I6e2LKkwI8z7H8UVVDXeEccG+7QK63cKXrPWfQWrUUUYjJVtIK2SRVnmYL/TuJJZpUkkA3w2rCpeIouKeVQyIj8IyzCXXLoA/ldWWnNcyVZp3kdKaeIKM20tFBxvlByJJQLsFsci25uR9mnYCFvdhea5GXBdTu7kNa3QYip/aomF5JtElHgngwcVrcek+sDun6WSrNGQI2Npbjee9QwxEvWFfIs6uZMS/ysxzc5hLxvg7b99UogxQHE9sqwAOMW3BzcdEznTBuOgOLpWCwJWzk70FBd325H+qDYR/+h1MQbkITET9IPEmDxVqgG7p3aQVKEnfI8CG0nZaMI8AUX8yndcp/rH0JGo+tj2ap9Sv856/LM2oSQy/qDnR9BNc/uh6k345CfR5JYBTZQ9QJz00N2bGQ2xPH48/d8vVVsYEK4iLQp1RWt+0ZPnZ9cpX1rsrPHeenFuG6aZhFs0b4Lqc7YywKhfoOCJDJgc39DqEwnR7swN+aiiV3AyB1AbZ+JL/tnWXdDCaxwMNILvFkhbQxf9yu3b32C+StO/HX48V6caCQg3HAiAYU19HHvcj9UCqE6BdOBYlGP9Fb61qjI7VRKBzwTYUs7N/sCtT9qZKJN3sXCdXbr6J74CBSRk+dUNJ87CSgIvXqhmfDFGsjmZ1EFsZEqz4XRxCylV9m0S60LX3qLTn5EQEamaCy877SnP//Cc9+henjO8vw6QzTecu/NakQx5y"
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque