apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    token: "AgAw90oP+WCWI1J9kmpOCZLbLZdJr5ZWHD8w0n23UnnPwe9ZEKp/M2gRs1IAuXIgn5qU4GMaYtUYfAZSUWM6AB9HbrwqaQnVC1A058NtjsE6ke5Biu3ba1UxLTxrPXU4WpZKYuKhdp+4qlDx96GZX8/ZFC14oYMkEWKeWkLpouw92bc9Dz7VZKkNMivnHDJ8EaA7U5SRbK/XtIM93+jGfivijMOu7t+yshaht/GAwTnf0GHj7rCUI4iNtwL1TbcE0tM0hh4T51TwcIccfDHMpZggA/aOyaeju9PFp/xeOegGa55QG6SxIrUUyN3nbjGYoagrgvsbmTZWbv0Fj79b+vYcMmrgkFNuTTNRoPVAfnAnPWSzBfTkwj7p1afqSBvIzLhmDBiP7ZNk3pYaSixAqiJPg8M8RTcS5YrPWpa2Pmpqpgk1KZAj+ucBA5MmzLpcXi3NlTdohTvG7xSuaRulLSkbhEfdzruyM4iUchR8MLGTs3+RmqowS1G1+7gNvmEObVjzpDAFZam7VeE/Mi3NlV9tNo7MgCd2Xnkhj6o38+Qn4Vda9LM99bY05/llDucarV6AQmTVJA9dZwMez2D1m34FEUtUZZG0gl6+UK2Sy5nzJK/EBNH/9ASb8sAEuWCOujNJx1egys5pDhdhEfHqoC+yXF9ZZffdPryrh74qboxGzry51vl1u0kJNp4+ZNsosac4psdZylYLaQ8oVoT8h+q86AsmAOY53Eh2wn2Jm9qS00BridGmIBUKvCCcmqvOnGzv0reakJttyh/ioREgTjxWwMvdju66eLLZYB+dWcv/qCzH1CNj8nXCwf7lLylZD9qfoECbUU2u8G28Yg6CU+lrd9HBYhtkP6nJ1yyYuOrHlRmg72frXipELa29WPwnLEZr4PBoXWTiRZ9IQgX3D/ddYEtrYhc4D864JWfjNdQu/cgGzwbDIi0W"
  template:
    metadata:
      name: tunnel-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque