apiVersion: v2
name: grafana-alloy
type: application

version: 1.0.0

dependencies:
  - name: alloy
    alias: grafana-alloy
    version: 1.0.3
    repository: "https://grafana.github.io/helm-charts"
