apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: printcost
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`printcost.home.daandewilde.be`)
      kind: Rule
      middlewares:
        - name: crowdsec-bouncer
          namespace: kube-system
      services:
        - name: printcost-printcost
          port: 8080
  tls: {}
