apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: kube-system
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgAB8Ze/KnAdzkRPhWdKRniww11/pFG3oVUjFCMcwt5H+kki6nd1yG145tzyHSEB4WBV4HgK1T8pUoiGmNaPKfiev00d+B109UFWLhPXYjYOsozfS4Z4NY3EQFbeuVFJ9ppQ/pmfETVsma6ecuiSWhcFqAwcsAiHg9kM5+twfZ3IBLlzMIyAQHaQ33TPL1206m5teF8rfdnIZnFTBi43qZ2WnF/TP2IGW6OltMdC4VgdVxwaoVd4LeXxG01Xa3gGVRb9zYr3k9rs6ztXA1GZbpSt47rz+uGlQKclBLvAJhbv9yMlP0RpN7iHffkeYGLrW53/4eo17Oo+Tt4WVerVoI5J3COxtwfKn7woYDwWr6IfSvSYKeoDHCivjp8teKdBy/NUV+dia3ab8Z5bs5nust7eF/VkgncimbUmQu8Uyk5BWTMvh8vBPrNXNLO6ClZYp3JEPDH0fnUW0lr9oUS7DXvafTAKMBO0HUA0xwW3D6YfDBl0uY6qIxMyxyUticaVTjQJkgMIDcRLpHp+y5gYpvUNCCroJL3O2po6EOR8yE69vYklbaNw0qPFpuFjxW2rtV7uclQCtRd9n7azvCJIdrl2Xrlg+lVEaNA1D1io8yqz1ceYTdKb0lbFQtDbXVx57i8cFD/BixzdYmxZZYc+NE0nZ8StzDAIjKqbVNX7dCDmDwFfc8yCh8Rpbs1owu+zVOkMNGHw2ibu4LnX6jiRRbTSQDRCzTC1bGOFBsfUiJ33WHizNUoDFHtiqAZd9TByMFMv2TlZmcVxOgJ3BJ//65F4
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: kube-system
    type: Opaque