apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgB1NQSOAwpZLU5A+DTNXpBb/Bcb6C0/UYEQnKJpEORG0K4w5Nb05kViToyL2mvMLgw50lCTn4j45P+aOkPZwBvLF/oksdwcor34//tF9vVEYdTJuPAFyluEdqGg0kkUP4t7tEITu+jiRJt46HRdwRMJ4XXx1P/SQRqGH5elCzacLcEWBlN0QC9jAwDS0tDZPD/dxStbwUDcuchQmwbqgNba1wmqFZT3O7kqgfNX6ftfTA2qFATz8u1nK37DQqKfg7Hqu0en2KylJLl0V3Hq25TXHCVyzxeKoD7SxUgY46lKnC0/9SYp54FdqpHTWXo+Q6FiGRuVHJ0SsJ7QbhdWIIAplL7zhuXhPj88b5cecrZOPMTkX+c50AID1QkU/J7Rzd/EBYRhwR7FbI1OPjMJYOOP8u15oOabimIdctVXCf4aN4ZhLNi39WpyYAE8J5lwyocyf3OPGvoIIUYLt8KDfpfjQWi4mAWNJTxMSrdbJqd/U7j+3MsTLtE/NibocCIGs2n4dqV2xYei5nVR4fTAtPK6jAL0Fv75bOqq4x440inuE7U6NfN2S7t03bpdodEUP6QkVnMZvN+Zp9mLTEka2qIvM7Q2jhJdXKZLRJ9pIDTEoSTC3qWfeE8AY6B1uYtIJIGbkcHip8KVpiTBu1rGWDicR2HSisab1XpmjR9PftWtb39dDL5vZLIoWeVoL5kM0Svv/tk/YOFfSpHEcbMssdsUs8VlPsudJG+D28GnBsrXCc/BUYRGZsvstJpeMtgwBgOWa9G0gbS46XaMUBPF2pG0
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
    type: Opaque