image:
  repository: ghcr.io/anyesh/wardrowbe
  backendTag: "backend-1.5.1"
  frontendTag: "frontend-1.5.1"
  pullPolicy: IfNotPresent

ingress:
  host: wardrobe.home.daandewilde.be
  url: https://wardrobe.home.daandewilde.be

persistence:
  storageClass: nfs-nas
  size: 100Gi

# CloudNativePG cluster
db:
  host: wardrowbe-db-rw
  user: wardrowbe
  name: wardrowbe
  appSecret: wardrowbe-db-app

# redis-operator Redis CR
redis:
  host: wardrowbe-redis

ai:
  internalEnabled: true
  visionEnabled: true
  textEnabled: true
  baseUrl: http://ollama.ollama.svc.cluster.local:11434/v1
  apiKey: not-needed
  visionModel: gemma3:4b
  textModel: gemma3:4b
  timeout: 600
  maxRetries: 3

oidc:
  issuerUrl: https://auth.home.daandewilde.be
  clientId: "1b238c41-9696-4455-8cb6-2b6d4e46066a"

secrets:
  name: wardrowbe-secrets
  encryptedSecretKey: "AgCbZ5UVwRFlfyYdUpFfx0k1k9qWNvznSuVn1vJQ+gu2zTloNK67SwbFzXwUHypZyUfIFHURcw8k9dp4mdsMKuy/7Z9oXis2kVIOvXtLrKxWE4KDj/aNGxLM/lAZExzoIKMeOTC+ofbHELdDUOhOu8D9hHr5H5m5JmzLlCA0dDhSptOEFOSCzswQVFL7Tkz8ckNljYw8kPzSxfDW9aoj6NQ6Qb7lzr/1V2OLIztK1gEP7NyOsheC5tuD13jPnc7kl5/TShMJEILUFTmE9pKmNXAd9ZI9B2eRsjlVPnvX9fBIgMubpsDdLejSaWHcZATjNTcHu9SL973ucKKXLmDonYQK1QTfiPHCo1AEMq+PqsCL2s9pTZbvuM1KnJDMWQj7Pn4fWbCIlQ6emIbO3f0fAC6i62OmCTdy1eFpnhnJu05tVZqCKt0XHWIdl72uN3OM3Fos3vkaGRhZrGVldJs43NqlyJqvOQBRAMydhw4rYPJf0toQ75NXCPReQcv79JvFjyuekaHxQuIXLzDnx+3BXG9Kvg93rnsGfZziwYGKcg0YtDJRa2CIbcrC2U+hVHInqNvq0mqwkJhnjPX/DI9mDD8Dw4ur+XA/CErSnRWtreYTezLBj0u8MpceHPDqHZhOhoaMrJa68V9bvexNtL15D/83qMBsPq95j70fd7/HYuTS1dle74XsCynvhYKebkRwltAnfgWeFlCdnUrZnXWImSBLOQGMZujcR2tvwKqUdzijyfW187ZzV/08JXZ2f9g3Uq8UfJYjCYs6Sg73G10gcyJT"
  encryptedNextauthSecret: "AgDFawGl5MtLhIeYLT0+mGwB3ccqXd90B1CZBai8FEhZnGBUy5Zokqn/DXXWHVSQt1RsU05XtFMAqj6+MJYC3eGjWykgnzCy2b4nOJtzuya7wseVUucTOlIKzWhOoGKS3ONH7biBgwaB46jquW2WSngfBAOTyG58QZWH//KW+U4Yw405ZVGHMsdTx0TB8y1uCyI+X54AxwuwnRFmFskCi0kT+JYZ++Jy3PyJ21PkD/whdV5h3f9JhuoiU+MDi8uAejzQvQpWBvnC3Y4JtS04EGMN99LiGS10rqYpD+Ki+uO8awcz8DwWL//njMeuvj7o42whgl9OBDBgvSl1Co9tVIBmyVsh0ciJRRi0W2BgfVB/sreNJJlvitlsRdaDq21VJ1aK1Gs0+ftanBllL4yUTo19GQjnZlWo8ZqcdQ8L1X8RS1YoauOWrn9zwEfRQ4WtszaKM0wEc/ao15zn3UpcCOkIHkANrSz/SbkhEx4JP7APDGTRh1UKVlcoTlCBInejdbJPRTxtz4MygEp2RCOR5u1i0YYaVgLyFT82n9IKibdtafv2O2kB2bTeHJ/HqV2s/s/GNxAc+EouT9k8yzpjogG9A666JOL3Di9OJa+0l3LdWoLxhEIJ0e5inqXBbav/RmaNLUFzn/ErIWvRVLQNMcWivEy39eINVfMvWJlwJZkFZgt8B09hJCZuT1b5mWOv3ZwXO9iZB/VNus14qBAKrbeSRN4Fdcws5DXtZ7n8vj+37lQJDIKdEzdDqo6CJzZcuWGa68xvTJ+YbaUhAdjMfNif"
  encryptedOidcClientSecret: "AgA08Fedv6XroTdShq0xD3zxbs+O6a5JzRMbMILZduQPQgBweLfTK14OnL5d0MkrNMbqAhsVmh6mMhHG5MKuAkj169qvZGDRaFwRKzNtCmOPWCdVjSit1E9gon/gf7ruUVd1nrUu/CXAM89ViX81lQ+RPeJRmISE89SjMlj15jfNd8lQTZhOlmqNnlTGE4UxwdzAz9jjILBJ8lMf8jKKC8tSzJLu9Nan0UX5n8qsPZl8z9Mnwij7qCqLEP+vTUhrvyWbsCq+cwYKAdSDLiGHAr9P6cF9iUg1C9diIMfq20fSYgA/fPLdLSu0G7M1+QO5NfWKVogHe/mysvMOslZpvvQ5PNTAT2gnenFEordON0a8f5zxNcc5rjbr5BJ4Sv7UaQpR5xlah8UJMZiSH4+PKOWc8/fi174ZrNRPU2pn4ILt0ua0c2HeWcTzUmniR2V+Kny6YVZQTlRzc81YqS9nrefKHuJ/3mKlgBOazLNdU0bryQuE4XBKMviAGvWEy2g8TANjqvrmLtl0mHvLD8bIIrA5jGsENS7pMmFWIQ/x50Or004m8LAcnYexR72baDiXvZoCPSC0w/MDIpP5lcVMs5/bdTDJyD1AdILTuavEz5IfHufX/da1+8gepq8Pb1wmHj15Z4jceQAv/2iM/6X0YvLlvwdFAr+Dj20+hAx/4wWjJRHT5xokLwJ8Z2HE1KuFqvoztEob5/RyfJLfm8GWj/UJgRCzmN/4VL8vxeW6ZcZM0g=="
  encryptedRedisPassword: "AgBhT8T7Yk3W5JvpSOp7c4Disd0rN/2zpVA2eJQQA3NsxIeZ4qIN6cGHSpjLu9d3IQKKtf8XMPYDy8spJRnTUPPlo1Bc9pErdUGcek7u86i1OWoMGzhfMhBmCbCqjCrbzCnAVbkyXlSB7cL8kReft3Z1KofbGM0PD/4OR3p7Ph5utX7WJ4XIvQVeIQ3+mzWiFVVBCsrJjEWDM2bP7xSk1Lqhsolkph0xSL6UW1uyGUhq1GWF8ypSJPa92tXQxIPWFNdtyQIndOXaWQ9qlpk9Yig6XAmSupLMh9e60J0day5La6rQvnCSHBFK+EKSwKIuehxXRR5FvxD/8DOu/HuLDuZRcjMB+SFEyJ+HfUxMpyzoy5hML1OodTCjBX9tMAUBsM2X++Z+TMn4TsMNOWKJnuo3rRBhNp60U9O1UmmYHk2z/1eHZ2F3X/wyzCKf1Q49fg02uIjS+O3NAMwlx1Dil8NuQN1udyD522ZBRzuarFNstrKOVLVRRQU8Y5YCZy7ptbcFoRwztNC5V2oCmH5K9PHw6YE7B6oVa3jONsb9mRQEfaWRGctoSxelzeZzwaafre5sMPLqNWkvXbutGINaxtwoyMPjdZRYRHdU1Hnn/RHT5aa9FRfcetP5DCvsHdWdaR8VI4+E/FR0bprtT/lVTpv87sY75xq+sR3TG9KbbZt58ekfrWw1mjwk9yU2XejKXEdZ6BVPpFgDDHKfT4yOvPMQx/6XhRil2KzjR2ZP2LLBhg=="

backend:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

frontend:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi

worker:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
