apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    oidc.clientSecret: AgC3GJsSg0lcYFcgIWMv8ljUlge+bowZbs1zUjq91mhcnunkqcQnzyWFDY4qW9h6v1Cakbjm07GjcXK1bXX53fYHMjKKBn23OZnPcbx9vyHU2qT53ShK4wqs3MLYE1WCVGqhQ5Xa/DhzJTlXQDWVIiZLbwucsBRrUm8PE5Aca0A85nxJ6R28JxRkAn6j/nS6wmyKKtHFyo+GFOZyU0LtpSScHAIqV3IipVoycCOiGCrl+ECeUzvT8vEZvmtrWTxRfA3n7vtm6zA+t/U0wTZ9Zl7bWmZUT+mRGQZ8p4K1u8VVdHlp+ayT+6KED7NMPquWX8ydQ1JTD3MISmZnjj7L7r07+NrZnQlVwRgnOx6KsvW6tkSR/cee8UyQvgP77w1UScUjGVxw2Xzc477Yw9DJIz5eUtKQOanKnwdy/eASceD8zVv6a6WXaplwKHpdYgVSViYVRhBUiX6Hz40KhAjHv7ouR/ObohinabFiMDTr/ADiGtDKO9miwMdUJVXUyR3LI6N9l536YXmihIT2EM5bPgEgVLRuguw0QOa0H7muUvrpDRNapTK6yjOvETgGFbwmn4UgYicpHIqxpOo+Gkw4CzEhkvtcZN8yDi8FU4vb4ozWDIV3akJh9Aptd6KdKwqhuQKHldlFmJQf1ao6SqmDB8diwj8fmPU5KUw2bnwhdPnYy0oDa7dRzpcpiMbqKyLgViB/WAYdbGcmbIsbXbyH9A7xvNQZ24BUylHy0eOWzatFyQ==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque