apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    server.secretkey: AgDMZiqO1DDI4QD9J9z4liozAtpaAl0e+O+6Au+GD6MNp4dRNCfwFziWbuDG5ozkK1qo1Ugc+4qmqdRoteDMik6R6g7h8ZZt2O0K1Ie1liNDcAPrvXBM9+YJi80yyfN/rvALI051x4JrgqTvzO/8OTjC3xwXcMmK71RpuY3ulgu/NXvDgV0LvR1nPTqBVl5e+FFMMVh3tAKCYj52e3xNDyi+GRgLXrWhDWtF/HR7GacVwESKje7ITfRU44S0pkMz7OrIPIQBXHP4knnayoO1PbQUS3oTgZ54DBCAeKxSUR/LFjZLbhQc0rWjNG0EvzgqVecPP/no3TdlJs8pjrrtYBPoyuylWcEh+JqWkhvGZtPWtgejDxKTLcrWqKbY4ee2hx8cPh1RDOahovwA5k1sZVcWlgPE01pYWPjWGcgSn5A9cgsBooYAlX6HG0LyOcVn+4IsywGZGhgpXLZ1BEpodEwzUiyTs/Pepnf9nFJH0W9ONeQVHBgktxmXo7tPNRGWXNWVO6PjLkpjXdmYaxsisYxKD11k+rLWQO76j87yV9Ldh8sgfK0/sH2qIzQnLy09uWeV0+UFNezt/UoapXbutErFeQjmxVM8OzLt7XvB53s3GGaCNdKg0e3jwme7KqBFI9JKSHUPZExWFDsBD9Gkx2NcOJegtrJ3iid/7zsyw/jtAbB1pI7yuRNck+ln6V7lecL8NsKo1gtJ8E686FY0pZ2L9pskU8IeSWfzY21IO899LUF4X9CgtOj8fAvZjg==
  template:
    metadata:
      name: argocd-secret
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/part-of: argocd
    type: Opaque