apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    oidc.clientSecret: AgAWiLRiNXuBVVCFe5c03m3YQi35aNoQcTJt35Ye+lVJbWB2pswtZiwYHOSGAD/6nu61dN2W7H8i9zDMV7RFsFCjx2DhsZMJqDFJpJcVja7UU2I+Ilty3z7+6MBaj/e1xiROt1RHGYCuZOPpaeg8NjI1fhZg7bQwWQ2diz2WabhqLRS3YHm7CVVz5fak/K0fAyDZjV1HH3bDfuLxS/QkxDOid7TtHc5kvrE3ej/uUNIykr013+lR29PPFY0pchyfSD4j9FYa01bksOegRSOasOto+fXvmYxGUgQwx7v3Arpa5hRpKa8Xl8amnf+f9gLP5E2sk1TIOkOmNM9I4bJ4jP46trrcgJevtXP9urkzCmsxcnZUHJtvEfo3IkprG9LLe2Z+sQ3L50SQclcfRSm08OQJdCdcScMqJ9nGMcep08ix/rn91OzKG9PUBXK3+0M1EztAGiUzQCd2lz1zYmz8jY/NbH0bpZn9G+tLTzH4h33fjD4tEQfKGvmhWnC4Yj8erpTxru/WuETPeZlJGXsQLR5jehtGKK+a24CjQDsYkgBlejOxecGLd9z1ZxqsmSoOAVzFa/16GvxAntZtOixOMWLxLBDVSa3I7veAYoWQdyF8FAbanYsA+BljSVnzIl2dgsXiUASjYBWI5iNwFt2ao2xth9XhkJNB0pJpY/44932uGyg231sJgrN4FhCw37duTYudnoG1ViVmA5cpWGCz6CKA8CcQKuF1JA8kMHdo8xTqDw==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/part-of: argocd
    type: Opaque