apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    oidc.clientSecret: AgC9jXkth6ELIGuQXgLjm1nh2nbVtNuqZORywrgRjcBv3Myi0YVHV37ONkTlpGo3tR3anEWaeEDdVY2YdvZLlTl6UjWYihiNiF9NrhlwoXg9KxoJcAeBAGu9d2zrvofoWz5sB56yRG8gQ+TioECTLoZtcwF7OA8C2IWD0Q/Q4RTwKxtXw2I0dZbv1cOixXgnwb5zY8EQjP5XrNZkvrZP5ydNXUY4HLOmdu4DLU6kWdnj+wOrAdSBg+6eAIP8OWrJSfoor/Clqu35S+HLtESw9zNQPZdHzPHkYbl8VTGbJZ6G4/BeaAb4jcL/W2wJGZ8vygGEj1f2F+KyFyWsbAF/SD17B+WawvfM48tuooGoE9ieXGOnSqIW7MUNb3EbxSLwKnFUjjtvq3C0larJ0mQ/a0aR6hFnu1VAyw5xuTudcPFY1C3GZVbnDvvdAwiEjKAmWvddhEJDNbfHE5UqcUdXEWPv58RJ3A5A+6FzOvkSr1W8zqeOJp67pSJwGMBx1p01j6rkjPWHpwZj0eA3buxCl6PU5p7kmxiwYW9KgOc4Ba/a8OYt+pQcU2c6KMUc2b7aBIGFZx9IUw5vhqtPVm6cMpTX8Az7jBbtrEqLk7HgPaB9P5gXu9LQOOEoaORKcaaxsV6ZBHDxTqL/Wr6LkqlsV1Ri3bjSiMP9VLwYpm5rBWnPf6QHf0PLO/wmkpuXSN65JWAu1NKmCnhqU1/JCMhCg/zJqoDsh3xbCAiQ8gt6Cr8u4w==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque